# Generated by Django 3.1.7 on 2021-03-05 16:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('InACTIVE', 'InActive')], default='ACTIVE', max_length=20)),
                ('cell_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{9,12}$')])),
                ('role', models.CharField(choices=[('Admin', 'ADMIN'), ('Agent', 'AGENT'), ('User', 'USER')], default='Admin', max_length=20)),
                ('aadhar_id', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{12}$')])),
                ('PAN_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{5}[0-9]{4}[A-Z]$')])),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amt', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('EMI', models.IntegerField()),
                ('total_months', models.IntegerField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('APPROVED', 'Approved'), ('NOT_APPROVED', 'Not_Approved')], default='NEW', max_length=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent', to=settings.AUTH_USER_MODEL)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
